languageCode: "en-us"
title: "{{ .Title }}"
copyright: Template Footer
pluralizelisttitles: false
params:
    sortByFilePath: true
markup:
  goldmark:
    renderer:
      Unsafe: true
    parser:
      attribute:
        block: true
  highlight:
    style: github
menu:
  main:
    - identifier: overview
      name: Overview
      url: /
      weight: 1
    - identifier: archetypes-and-personas
      name: Archetypes and Personas
      url: /archetypes-and-personas/
      weight: 2
    - identifier: entities-and-relationships
      name: Entities and Relationships
      url: /entities-and-relationships/
      weight: 3
    - identifier: state-transitions
      name: State Transitions
      url: /state-transitions/
      weight: 4
    - identifier: features-and-funtions
      name: Features and Functions
      url: /features-and-functions/
      weight: 5
    - identifier: process-flows
      name: Process Flows
      url: /process-flows/
      weight: 6
    - identifier: capabilities
      name: Capabilities
      url: /capabilities/
      weight: 7
    - identifier: reference
      name: Reference
      url: /reference/
      weight: 8
    - identifier: updates
      name: Updates
      url: /updates/
      weight: 9
outputFormats:
  MenuIndex:
    baseName: menu
    mediaType: application/json
  SearchMap:
    baseName: searchmap
    mediaType: application/json
outputs:
  home:
    - HTML
    - RSS
    - MenuIndex
    - SearchMap
module:
  imports:
    {{ if .Brand -}}
    - path: {{ .Brand }}
      mounts:
        - source: assets
          target: assets
        - source: static
          target: static
    {{- end }}
    - path: {{ .Theme }}
enableInlineShortcodes: true
frontmatter:
  lastmod:
    - lastmod
    - :fileModTime
    - :default
