version: 2

before:
  hooks:
    - go mod tidy
    - make prepare-themes

builds:
  - tags:
      - extended
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: "386"
      - goos: windows
        goarch: "386"
      - goos: windows
        goarch: arm64
    hooks:
      post: make restore-themes

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - name: presidium
    homepage: "https://github.com/spandigital/presidium"
    description: "Presidium is a software documentation management system for agile teams"
    repository:
      owner: spandigital
      name: homebrew-tap
    directory: Formula
