env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
    - go install github.com/gobuffalo/packr/v2/packr2
    - packr2
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: macOS
      386: 32-bit
      amd64: 64-bit
release:
  prerelease: auto
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
#brews:
#  - goarm: 6
#    tap:
#      owner: SPANDigital
#      name: homebrew-tap
#      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
#    commit_author:
#      name: goreleaserbot
#      email: goreleaser@spandigital.com
#    folder: Formula
#    homepage: "https://github.com/SPANDigital/presidium-hugo"
#    description: "presidium is a software documentation management system for agile teams"
#    download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy
#    custom_require: "lib/private"
