languageCode: "en-us"
title: "{{ .Title }}"
copyright: Template Footer
pluralizelisttitles: false
params:
    sortByFilePath: true
markup:
  goldmark:
    renderer:
      Unsafe: true
    parser:
      attribute:
        block: true
  highlight:
    style: github
menu:
  main:
    - identifier: overview
      name: Overview
      url: /
      weight: 1
    - identifier: key-concepts
      name: Key Concepts
      url: /key-concepts/
      weight: 2
    - identifier: runbooks
      name: Runbooks
      url: /runbooks/
      weight: 3
    - identifier: SLAs
      name: SLAs
      url: /SLAs/
      weight: 4
    - identifier: glossary
      name: Glossary
      url: /glossary/
      weight: 5
outputFormats:
  MenuIndex:
    baseName: menu
    mediaType: application/json
  SearchMap:
    baseName: searchmap
    mediaType: application/json
outputs:
  home:
    - HTML
    - RSS
    - MenuIndex
    - SearchMap
module:
  imports:
    {{ if .Brand -}}
    - path: {{ .Brand }}
      mounts:
        - source: assets
          target: assets
        - source: static
          target: static
    {{- end }}
    - path: {{ .Theme }}
enableInlineShortcodes: true
frontmatter:
  lastmod:
    - lastmod
    - :fileModTime
    - :default
