name: Presidium
baseurl:
footer:
logo: media/images/logo.png
#
# Menu Structure. To include all articles add the collection.
#
structure:
  - title: "Overview"
    path: "/"

  - title: "Prerequisites"
    path: "/prerequisites/"

  - title: "Key Concepts"
    path: "/key-concepts/"

  - title: "Getting Started"
    path: "/getting-started/"
    collection: 'getting_started'

  - title: "References"
    path: "/references/"
    collection: "references"

  - title: "Recipes"
    path: "/recipes/"

  - title: "Tools"
    path: "/tools/"

  - title: "Testing & Debugging"
    path: "/testing/"

  - title: "Updates"
    path: "/updates/"

#
# Collections for content articles
#

collections:
    best_practices:
    getting_started:
    key_concepts:
    overview:
    prerequisites:
    recipes:
    references:
        output: true
        permalink: /references/:path/
    testing:
    tools:
    typical_scenarios:
    updates:

github:
  path:

#
# Exclude the following files from the generated site
#
exclude: [
    "README.md",
    "LICENSE",
    "_TEMPLATE.md",
    ".gitignore"
]

#
# System wide defaults
#
defaults:
    -
        scope:
            path: ""
        values:
            layout: "container"

#
# Sass settings
#
sass:
    sass_dir: media/css/_sass
