languageCode: en-us
title: "Presidium"
copyright: SPAN Digital
baseUrl: /
assetDir: static
pluralizelisttitles: false
enableGitInfo: false
markup:
  goldmark:
    renderer:
      Unsafe: true
  highlight:
    style: github
params:
  enterprise_key: presidium
  audience: ""
  description: ""
  logo: /images/logo.png
  roles:
    label: ""
    all: ""
    options: []
  scope: ""
  show:
    status: false
    author: false
    role: true
  frontmatter:
    - key: author
      strict: false
      type: email
    - key: title
      strict: true
      type: text
  lazyLoad: false
sectionPagesMenu: ""
menu:
  Main:
    - identifier: overview
      name: Overview
      url: /
      weight: 10
    - identifier: key-concepts
      name: Key Concepts
      url: /key-concepts/
      weight: 20
    - identifier: getting-started
      name: Getting Started
      url: /getting-started/
      weight: 30
    - identifier: presidium-basics
      name: Presidium Basics
      url: /presidium-basics/
      weight: 40
    - identifier: best-practices
      name: Best Practices
      url: /best-practices/
      weight: 70
outputFormats:
  MenuIndex:
    baseName: menu
    mediaType: application/json
  SearchMap:
    baseName: searchmap
    mediaType: application/json
outputs:
  home:
    - HTML
    - RSS
    - MenuIndex
    - SearchMap
module:
  imports:
    - path: github.com/spandigital/presidium-styling-base
    - path: github.com/spandigital/presidium-layouts-base
enableInlineShortcodes: true
frontmatter:
  lastmod:
    - lastmod
    - :fileModTime
    - :default
