name: goreleaser
on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    environment: releaser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Get packr
        run: go get -u github.com/gobuffalo/packr/v2/packr2
      - name: Prepare
        run: git reset --hard
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}