name: Test and Tag Code
on:
  - push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Run Tests
        run: make test
  version:
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'
    name: Version Code
    runs-on: ubuntu-latest
    needs:
      - test
    outputs:
      tag: ${{ steps.versioning.outputs.tag }}
      upload_url: ${{ steps.versioning.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v2
      - name: Version Commit
        id: versioning
        uses: afdecastro879/automatic-github-versioning-action@v0.1.10
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release:
    name: Release Code
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs:
      - version
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set Up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Create Release
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
