name: goreleaser

on:
  push:
    tags:
      - "*"

jobs:
  goreleaser:
    environment: releaser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.x
      - name: Prepare themes for embedding
        run: make prepare-themes
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ github.token }}
